/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AudioDB_Mode */

#ifndef _Included_AudioDB_Mode
#define _Included_AudioDB_Mode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
